/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_cchi_medthimager_thermalproc_ThermalDumpProcessor */

#ifndef _Included_tw_cchi_medthimager_thermalproc_ThermalDumpProcessor
#define _Included_tw_cchi_medthimager_thermalproc_ThermalDumpProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_MAX_ALLOWED
#define tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_MAX_ALLOWED 3931L
#undef tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_FILTER_RATIO_LOW
#define tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_FILTER_RATIO_LOW 0.005
#undef tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_FILTER_RATIO_HIGH
#define tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_FILTER_RATIO_HIGH 5.0E-4
/*
 * Class:     tw_cchi_medthimager_thermalproc_ThermalDumpProcessor
 * Method:    generateThermalImageNative
 * Signature: (FFJ)V
 */
JNIEXPORT void JNICALL Java_tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_generateThermalImageNative
  (JNIEnv *, jobject, jfloat, jfloat, jlong);

/*
 * Class:     tw_cchi_medthimager_thermalproc_ThermalDumpProcessor
 * Method:    cvtThermalValues10Native
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_cvtThermalValues10Native
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     tw_cchi_medthimager_thermalproc_ThermalDumpProcessor
 * Method:    updateThermalHistNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tw_cchi_medthimager_thermalproc_ThermalDumpProcessor_updateThermalHistNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
